//Version Info .

#ifndef _M_VER_
#define _M_VER_

//Icon Files .
#define VIconFileName "ICON1.ICO"

//File Version Number .
#define VFileVersion "1.0"

//Product Version Number .
#define VProductVersion "1.0"

//Other Version Details
#define VProductName "AfterBurn"
#define VCompanyName "ODE"
#define VLegalCopyright "Copyright © 2002-Present Karthik Kumar Viswanathan & Nikhil Karnad"
#define VLegalTrademarks "None"
#define VFileDescription "AfterBurn Video Game"
#define VComments "None"
#define VInternalName "AfterBurn"
#define VOriginalFilename "AB"

//Language Details
#define VCountry 0x409
#define VLanguage 1200

#endif //_M_VER_

